hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 999999999  
ribbon: 
  ReadTimeout: 999999999
  ConnectTimeout: 999999999
zuul:
    host:
        socket-timeout-millis: 999999999
        connect-timeout-millis: 999999999