hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 999999999  
ribbon: 
  ReadTimeout: 30000
  ConnectTimeout: 30000
zuul:
    host:
        socket-timeout-millis: 30000
        connect-timeout-millis: 30000